### ISSUE TITLE
MLflow for storing of models

### ISSUE THREAD

**Issue by jduijvenbode-WWF** [ForestForesight/ForestForesight#18]
**Is your feature request related to a problem? Please describe.**
We do not have a good history of our models and how well they perform. We want to use MLFlow or a similar tool for this

**Describe the solution you'd like**
Have a simple to manage cloud solution of MLFlow that will fetch the latest per country, country group or global model that works best for that area. Have this implemented in ff_predict and ff_run (and maybe ff_sync?)

**Describe alternatives you've considered**
We currently just have one model and an experimentation and accuracy folder. They are not being maintained well or in a structured way

**Additional context**
MLFlow on databricks seems to require bash or python to connect with, which is annoying because we want it to be R-based

**Comment by hasruleng** [comment]
@jduijvenbode-WWF last night I succesfully using R to store its experiment to my local MLflow. 
I think the best approach to use MLflow with R is to work with Python first. As python is the most supported for MLflow, we need to patiently test each line of python mlflow to work in R.

**Comment by jduijvenbode-WWF** [comment]
this has been turned into a project
