### ISSUE TITLE
Saving prediction f_score to local

### ISSUE THREAD

**Issue by maasva** [ForestForesight/ForestForesight#26]
**Is your feature request related to a problem? Please describe.**
Hi! I would like to be able to save my f_score locally when running ff_predict. 

**Describe the solution you'd like**
A function that helps me save the f_score of a prediction locally. 

**Describe alternatives you've considered**
Copying by hand but that just seems silly in this day and age. 

**Additional context**
I saw the ff_predict can use some refactoring anyway. So I will do that too. I already started, please take a look quickly, thank you!

**Comment by jduijvenbode-WWF** [comment]
no this is done in ff_analyze already. also some functions return the F05 score so you can save it manually from there. but thanks for your input and we look forward to serving you as a valuable customer in the future!
