### ISSUE TITLE
determine the unit of experiments and runs

### ISSUE THREAD

**Issue by jduijvenbode-WWF** [ForestForesight/ForestForesight#48]
in mlflow you can create experiments, which can then host runs. These runs can then be combined in a many-to-many relationship with tags.

we need to determine:
a) what the names of the experiments will be
b) what the unit of the runs will be
c) what the tags of these runs will be

**Comment by jduijvenbode-WWF** [comment]
option 1:
experiments are the regions, runs are the different methods and we add tags to explain the method
option 2:
experiments are the different methods, runs are the different regions.

Pros of Region-based Experiments:

Natural isolation of regions - easier to focus on one region's performance
Cleaner visualization in MLflow UI for single-region analysis
Parallel development/updates possible without cluttering other regions
Easier to manage permissions if different teams handle different regions
Simpler to track region-specific model evolution over time

Cons of Region-based Experiments:

Harder to compare across regions for the same iteration
More experiments to manage (41 instead of 1)
Cross-region analysis requires querying multiple experiments
More complex to ensure consistency across all regional experiments
Harder to track complete iteration rollouts

I favor the region-based experiments because end-users will look at this from region to region and we already know that different methods work better for different regions and no method is optimal

**Comment by ZillahCalle** [comment]
I agree! It also helps to select the best model per region.
