### ISSUE TITLE
Configure file paths and other environment variables through a config file

### ISSUE THREAD

**Issue by maasva** [ForestForesight/ForestForesight#5]
**Is your feature request related to a problem? Please describe.**
It will be much easier to use the software if I don't have to dig into the codebase to change environment variables manually. Plus it might be easier to have paths to data in a config file so I won't have to use them as an input parameter.

**Describe the solution you'd like**
I would like a file I can use and load into my environment to set my environment variables and paths, and that that file is automatically used by the code. 

**Describe alternatives you've considered**
Potentially create a function in which you can input all your variables once at the start of each session such that they can be used throughout the session after, but that seems a bit more bothersome. 

**Additional context**

**Comment by jduijvenbode-WWF** [comment]
would this work @maasva :
# R/zzz.R

.onLoad <- function(libname, pkgname) {
  config <- load_config()
  assign("config", config, envir = parent.env(environment()))
}

# For debugging/testing during development
.onAttach <- function(libname, pkgname) {
  packageStartupMessage("Config loaded from: ", config$source)
}

according to Claude this should autoload the config file when loading the ForestForesight package
