### ISSUE TITLE
determine which parameters and metrics should be stored

### ISSUE THREAD

**Issue by jduijvenbode-WWF** [ForestForesight/ForestForesight#50]
perhaps all the xgb.booster input parameters, training dates, validation dates, precision, recall F05 (and F1?) and feature list
- eta
- gamma
- subsample
- max_depth
- data sample fraction
- validation sample fraction
- start date training
- end date training
- validation date start
- validation date end
- lambda
- nrounds
- eval_metric
- stopping_rounds
- minimum child weight
- objective

- precision
- recall
- F0.5
- TP
- FP
- FN
- AUC

-feature list

**Comment by ZillahCalle** [comment]
I agree!
