### ISSUE TITLE
Code improvements

### ISSUE THREAD

**Issue by maasva** [ForestForesight/ForestForesight#6]
**Is your feature request related to a problem? Please describe.**
I am trying to make some changes to the ff_prep function. However, because it is a really big function it is hard to find my way through it. It would be nice if the codebase is updated to adhere better to software engineering principles. Additionally, I'm a bit afraid that when I make changes I might break something unintentionally because there seems to be no test cases. 

**Describe the solution you'd like**
I'd like the code to adhere better to software engineering principles like functional decomposition and unit testing. Such that contribution becomes easier and the software is more robust and easier to change. 

**Describe alternatives you've considered**
I've considered just pushing through the pain of understanding the functions in their current state, but it is difficult and I can't imagine that no-one else is facing similar problems. 

**Additional context**

**Comment by jduijvenbode-WWF** [comment]
this one can be claused because it is an example
