### ISSUE TITLE
when loading forestforesight it shows a warning on the densify function

### ISSUE THREAD

**Issue by jduijvenbode-WWF** [ForestForesight/ForestForesight#71]
**Describe the bug**
it shows during installing Warning: replacing previous import 'smoothr::densify' by 'terra::densify' when loading 'ForestForesight'

this is really annoying because it seems something is going on. it can be easily fixed by adding to the .onLoad function:

.onLoad <- function(libname, pkgname) {
  conflicted::conflicts_prefer(terra::densify)
}
I'm waiting on the merging of pull request #65

**Comment by hasruleng** [comment]
Hi Jonas @jduijvenbode-WWF 
I would like to fix all warnings that happen during onLoad

**Comment by jduijvenbode-WWF** [comment]
great!

**Comment by jduijvenbode-WWF** [comment]
it needs to install the conflicted package, otherwise it doesn't work

**Comment by jduijvenbode-WWF** [comment]
for now we'll let this rest as i dont expect any issues with the resolve package and this is better than it was
