### ISSUE TITLE
ff_train lost its roxygen2 code

### ISSUE THREAD

**Issue by jduijvenbode-WWF** [ForestForesight/ForestForesight#74]
**Describe the bug**
ff_train does not have any documentation or examples anymore

**To Reproduce**
Load the package
type ?ff_Train
see with your own eyes with that it is gone

**Expected behavior**

**Screenshots**

**Additional context**
It can probably be copied from the main branch and updated with an LLM without any typing needed

**Comment by hasruleng** [comment]
I think I can do this

**Comment by jduijvenbode-WWF** [comment]
fixed
