### ISSUE TITLE
New contributor documentation

### ISSUE THREAD

**Issue by maasva** [ForestForesight/ForestForesight#9]
**Is your feature request related to a problem? Please describe.**
I want to start contributing but I have trouble with finding the exact development workflows and extra documentation to start. Could this potentially be added. I really want to help but currently don't know how. 

**Describe the solution you'd like**
I would like a contribution.md that can guide me through my contributions. Additionally, some templates and stuff for PR requests and issues (like this one, it's really nice) would be really handly. All additional information sources are also welcome. 

**Describe alternatives you've considered**
I mean, I could just start, but I want to be sure that my work isn't wasted. 

**Additional context**

**Comment by aminbksi** [comment]
for all the templates such as pull request and contributing, there are some mds added, which needs to be improved and fixed. I am going to send a PR for it. @maasva
